apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: federation
    service: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80