apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: auth
  labels:
    app: federation
    service: auth
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: auth
  template:
    metadata:
      name: auth
      labels:
        app: auth
        service: auth
    spec:
      containers:
        - name: auth
          image: localhost:5000/nxsdvlpr/federation_auth:latest
          ports:    
            - containerPort: 4100