apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gateway
  labels:
    app: federation
    service: gateway
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
        service: gateway
    spec:
      containers:
        - name: gateway
          image: localhost:5000/nxsdvlpr/federation_gateway:latest
          ports:    
            - containerPort: 4000