apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: federation
    service: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - port: 4000
      targetPort: 4000