apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: base
  labels:
    app: federation
    service: base
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: base
  template:
    metadata:
      name: base
      labels:
        app: base
        service: base
    spec:
      containers:
        - name: base
          image: localhost:5000/nxsdvlpr/federation_base:latest
          ports:    
            - containerPort: 4400